# Site settings
title: Robert R. Denton
email: rob@robertrdenton.com
description: Rob is a web guy at a newspaper. He wrangles a CMS and fixes things that break.
# baseurl: "" 
url: "http://robertrdenton.com"
twitter_username: robertrdenton
github_username:  robertdenton

# Build settings
markdown: kramdown
